#define WIND_SPEED_PIN 27
#define WIND_DIR_PIN 28
#define WIND_DIR_ADC 2
#define RAIN_BUCKET_PIN 9
#define I2C_SDA_PIN 20
#define I2C_SCK_PIN 21

#define CLICK_AN_ADC 0
#define CLICK_AN_PIN 26
#define CLICK_RST_PIN 22
#define CLICK_TX_PIN 13
#define CLICK_RX_PIN 12
#define CLICK_INT_PIN 14
#define CLICK_CS_PIN 17
#define CLICK_SCK_PIN 18
#define CLICK_MISO_PIN 16
#define CLICK_MOSI_PIN 19
#define CLICK_SDA_PIN 10
#define CLICK_SCL_PIN 11
#define CLICK_PWM_PIN 15

#define WIND_LED_PIN 8
#define RAIN_LED_PIN 7
#define GPS_LED_PIN 3
#define BMP_LED_PIN 2
#define TMP_LED_PIN 1
#define REPORT_LED_PIN 0
#define VSYS_PIN 29
#define VSYS_ADC 3